String BASE_URL = "https://api.covid19api.com/";
String SUMMARY = "summary";
String NewDeaths = "New Deaths : ";
String NewRecoovered = "New Recovered : ";
String NewConfirmed = "New Confirmed : ";
String TotalConfirmed = "Total Confirmed : ";
String TotalDeaths = "Total Deaths : ";
String TotalRecovered = "Total Recovered : ";
String TheDateForStatus = "Date : ";
